language: node_js
sudo: enabled
install: npm install
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
services: mysql
script: node ./model/sync/init-area.js && node ./model/sync/init-gym.js && node ./model/sync/init-new.js && node ./model/sync/init-new_type.js && node ./model/sync/init-reserve.js && node ./model/sync/init-site.js && node ./model/sync/init-sport.js && node ./model/sync/init-type.js && set NODE_ENV=test&&node app.js

