language: node_js
node_js: 8.11.1
env: NODE_ENV=test
sudo: enabled
install: npm install
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
services: mysql
script: node ./app/model/sync/init-area.js && node ./app/model/sync/init-gym.js && node ./app/model/sync/init-new.js && node ./app/model/sync/init-new_type.js && node ./app/model/sync/init-reserve.js && node ./app/model/sync/init-site.js && node ./app/model/sync/init-sport.js && node ./app/model/sync/init-type.js && node app.js

